module.exports = {
  CHECK_ACCOUNT_REQUEST: "account/CHECK_ACCOUNT_REQUEST",
  CHECK_ACCOUNT_SUCCESS: "account/CHECK_ACCOUNT_SUCCESS",
  CHECK_ACCOUNT_FAILURE: "account/CHECK_ACCOUNT_FAILURE",
  CREATE_ACCOUNT_REQUEST: "account/CREATE_ACCOUNT_REQUEST",
  CREATE_ACCOUNT_SUCCESS: "account/CREATE_ACCOUNT_SUCCESS",
  CREATE_ACCOUNT_FAILURE: "account/CREATE_ACCOUNT_FAILURE"
};
