module.exports = {
  LOGIN_REQUEST: "auth/LOGIN_REQUEST",
  LOGIN_SUCCESS: "auth/LOGIN_SUCCESS",
  LOGIN_FAILURE: "auth/LOGIN_FAILURE",
  DOMAIN_REQUEST: "auth/DOMAIN_REQUEST",
  DOMAIN_SUCCESS: "auth/DOMAIN_SUCCESS",
  DOMAIN_FAILURE: "auth/DOMAIN_FAILURE",
  LOGOUT_ACTION: "auth/LOGOUT_ACTION"
};
