module.exports = {
  LOGIN_REQUEST: "auth/LOGIN_REQUEST",
  LOGIN_SUCCESS: "auth/LOGIN_SUCCESS",
  LOGIN_FAILURE: "auth/LOGIN_FAILURE",
  DOMAIN_REQUEST: "auth/DOMAIN_REQUEST",
  DOMAIN_SUCCESS: "auth/DOMAIN_SUCCESS",
  DOMAIN_FAILURE: "auth/DOMAIN_FAILURE",
  CHECK_DOMAIN_REQUEST: "auth/CHECK_DOMAIN_REQUEST",
  CHECK_DOMAIN_SUCCESS: "auth/CHECK_DOMAIN_SUCCESS",
  CHECK_DOMAIN_FAILURE: "auth/CHECK_DOMAIN_FAILURE",
  ADDRESS_REQUEST: "auth/ADDRESS_REQUEST",
  ADDRESS_SUCCESS: "auth/ADDRESS_SUCCESS",
  ADDRESS_FAILURE: "auth/ADDRESS_FAILURE",
  LOGOUT_ACTION: "auth/LOGOUT_ACTION"
};
