module.exports = {
  CREATE_DOMAIN: "fitness/CREATE_DOMAIN",
  CHECK_FITNESS_REQUEST: "fitness/CHECK_FITNESS_REQUEST",
  CHECK_FITNESS_SUCCESS: "fitness/CHECK_FITNESS_SUCCESS",
  CHECK_FITNESS_FAILURE: "fitness/CHECK_FITNESS_FAILURE",
  CREATE_FITNESS_REQUEST: "fitness/CREATE_FITNESS_REQUEST",
  CREATE_FITNESS_SUCCESS: "fitness/CREATE_FITNESS_SUCCESS",
  CREATE_FITNESS_FAILURE: "fitness/CREATE_FITNESS_FAILURE"
};
